-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.guest CASCADE;
DROP TABLE IF EXISTS public.checkin CASCADE;

CREATE TABLE IF NOT EXISTS public.guest
(
    guest_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying(90) NOT NULL,
    document_number character varying(12) NOT NULL,
    phone character varying(12) NOT NULL,
    PRIMARY KEY (guest_id)
);

CREATE TABLE IF NOT EXISTS public.checkin
(
    checkin_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
	guest_id integer NOT NULL,
    checkin_date date NOT NULL,
    checkout_date date,
    has_vehicle boolean NOT NULL DEFAULT false,
    PRIMARY KEY (checkin_id)
);

ALTER TABLE IF EXISTS public.checkin
    ADD CONSTRAINT guest_fkey FOREIGN KEY (guest_id)
    REFERENCES public.guest (guest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;